### PR TITLE
Fix handling large seed values

### LINKED ISSUE #1003: cmdstan random seed not reading correctly (seems like a 32bit thing?)
#### Summary:

I ran a model and it gave me as output:

```
data
  file = lv.json
init = 2 (Default)
random
  seed = 2431820427
```

And then I tried to run it again with: 
```
./lv sample data file=lv.json random seed=2431820427
```

And I got:
```
2431820427 is not a valid value for "seed"
  Valid values: integer >= 0 or -1 to generate seed from system time
Failed to parse command arguments, cannot run model.
```

2^31 = 2147483648

I assume somewhere in the I/O we're reading this as a signed 32 bit int and it should be unsigned 32 bit.

#### Current Version:
v2.26.1

### PR DESCRIPTION
**Pull request by rok-cesnovar**
#### Summary:

Fixes #1003 by allowing values up to max `unsigned int`.

To test run the following with the bernoulli example:

This fails on develop but works on this PR
```
./examples/bernoulli/bernoulli sample data file=examples/bernoulli/bernoulli.data.json random seed=2147483647
```

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):
Rok Češnovar

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

File: src/test/interface/command_test.cpp [hunk 1]
```diff
@@ -496,8 +496,9 @@ TEST(StanUiCommand, random_seed_fail_2) {
   model_path.push_back("test-models");
   model_path.push_back("transformed_data_rng_test");
 
-  int max = std::numeric_limits<int>::max();
-  unsigned int maxplus = max + 100;
+  long long int max = std::numeric_limits<unsigned int>::max();
+  long long int maxplus = max + 100;
+
```
Comment (bbbales2) [inline src/test/interface/command_test.cpp:501]: Add a test to make sure this runs with just max (equivalent of running the command in the PR).

I think if you check the error message isn't there with max and then is there with maxplus it's good enough:

```cpp
{
  std::string command
        = convert_model_path(model_path)
          + " sample num_samples=10 num_warmup=10 init=0 "
          + " random seed=" + std::to_string(max) + " "
          + " data file=src/test/test-models/transformed_data_rng_test.init.R"
          + " output refresh=0 file=test/output.csv";
    std::string cmd_output = run_command(command).output;
    run_command_output out = run_command(command);
    EXPECT_EQ(0, count_matches(expected_message, out.body));
}

{
  std::string command
        = convert_model_path(model_path)
          + " sample num_samples=10 num_warmup=10 init=0 "
          + " random seed=" + std::to_string(maxplus) + " "
          + " data file=src/test/test-models/transformed_data_rng_test.init.R"
          + " output refresh=0 file=test/output.csv";
    std::string cmd_output = run_command(command).output;
    run_command_output out = run_command(command);
    EXPECT_EQ(1, count_matches(expected_message, out.body));
}
```

Then seems good to me.

**Review by bbbales2 — CHANGES_REQUESTED** [review]

File: src/test/interface/command_test.cpp (hunk 1 above)
Comment (rok-cesnovar) [reply src/test/interface/command_test.cpp:501]: Thanks, added!

**Review by bbbales2 — APPROVED** [review]
