### PR TITLE
Runtime OpenCL device selection, allow seed=0 and fix allow-undefined user_header bug

### LINKED ISSUE #941: Why is seed = 0 not allowed
This is just a question, not really an issue. 

Why is seed=0 not allowed in cmdstan, but is in rstan? The check in cmdstan is seed > 0.

Any specific reason or just arbitrary?

### LINKED ISSUE #953: detect if model has no parameters and run fixed param sampler automatically
#### Summary:

When running the sampler on a model which doesn't have any parameters, the command program should be
able to detect whether or not the model has no parameters, and in this case, it should run fixed_param automatically.

#### Description:

It is extremely annoying to get the "fixed_param" error message when trying to use Stan programs to produce simulated data.

check here: https://github.com/stan-dev/cmdstan/blob/9b711ed1bd13db3d29c3df682333abe3813abb10/src/cmdstan/command.hpp#L390-L392

instead of quitting, the reasonable thing to do is run the non-adaptive sampler for the specified number of sampling iterations.

#### Reproducible Steps:

here's a datagen program in Stan:

```
// generate parameters, data, outcomes for poisson regression 
transformed data {
  int N_obs = 20;               // specify constants
}
generated quantities {
  int N = N_obs;
  int y_sim[N_obs];
  vector[N_obs] x_sim; 
  vector[N_obs] pop_sim;
  real alpha_sim;
  real beta_sim;
  real phi_sim;
  real mu[N_obs];  // mean

  alpha_sim = normal_rng(0, 1);  // simulate parameters
  beta_sim = normal_rng(0, 1);   // from prior
  while (1) {
    phi_sim = normal_rng(0, 1);
    if (phi_sim > 0) break;
  }

  for (n in 1:N_obs) {           // simulate data from params
    pop_sim[n] = uniform_rng(500,2500);
    x_sim[n] = uniform_rng(0.01,0.99);
    mu[n] = log(pop_sim[n]) + alpha_sim + x_sim[n] * beta_sim;
    y_sim[n] = neg_binomial_2_log_rng(mu[n], phi_sim);
  }
}
```

#### Current Output:
Run the Stan sampler - error message: "Must use algorithm=fixed_param for model that has no parameters."

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

Should just work.

#### Current Version:
v2.25.0

### PR DESCRIPTION
**Pull request by rok-cesnovar**
#### Summary:

Fixes one part of #825 
Fixes #941 
Fixes #953 

The main part of this PR is allowing runtime selection of OpenCL devices.

```
./examples/bernoulli/bernoulli sample data file=examples/bernoulli/bernoulli.data.json opencl platform=0 device=0
```
Specifying only platform or only device IDs will print
```
Please set both device and platform OpenCL IDs.
```
Using opencl args when the model was not compiled with STAN_OPENCL will print

```
opencl is either mistyped or misplaced.
Re-compile the model with STAN_OPENCL to use OpenCL CmdStan arguments.
Failed to parse arguments, terminating Stan
```

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Rok Češnovar

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

File: make/program [hunk 1]
```diff
@@ -29,7 +29,7 @@ CXXFLAGS_PROGRAM += -include-pch $(STAN)src/stan/model/model_header$(STAN_FLAGS)
 $(STAN_TARGETS) examples/bernoulli/bernoulli$(EXE) $(patsubst %.stan,%$(EXE),$(wildcard src/test/test-models/*.stan)) : %$(EXE) : $(STAN)src/stan/model/model_header$(STAN_FLAGS).hpp.gch
 endif
 
-ifneq ($(findstring allow_undefined,$(STANCFLAGS)),)
+ifneq ($(findstring allow_undefined,$(STANCFLAGS))$(findstring allow-undefined,$(STANCFLAGS)),)
```
Comment (rok-cesnovar) [inline make/program:32]: This is a minor fix for #953

File: src/cmdstan/arguments/arg_seed.hpp [hunk 2]
```diff
@@ -25,7 +25,7 @@ class arg_seed : public int_argument {
               .total_milliseconds();
   }
 
-  bool is_valid(int value) { return value > 0 || value == _default_value; }
+  bool is_valid(int value) { return value >= 0 || value == _default_value; }
```
Comment (rok-cesnovar) [inline src/cmdstan/arguments/arg_seed.hpp:28]: The changes to this file is a fix for #941

**Review by SteveBronder — APPROVED** [review]
lgtm!
